### ISSUE TITLE
OpenSHC on X-series Dynamixels and Jetson Nano

### ISSUE THREAD

**Issue by MatthewOliverKing** [csiro-robotics/shc_tutorials#3]
I am running into problems implementing OpenSHC on my hexapod with Jetson Nano (Melodic, Ubuntu 18.04) and Dynamixel XL-430 and 2XL-430 motors. 

Since the X-series are newer than any tested on OpenSHC before, we have had to adapt the dynamixel_const.py file to suit the X-series control table, and change some of the dynamixel_io.py functions to return correct values. Pinging the motors and echoing the motor_states/dynamixel_port topic shows the information is being communicated correctly:

![motostates](https://user-images.githubusercontent.com/85664248/131777070-13a12291-7695-478d-9c23-4dc36351590c.png)

However, we have this debug error:

<debug error>

And a few node subscriptions (most noticeably the /syropod//<legID>_<jointID>/command topics) are unconnected:

![CaveX_rqt_graph](https://user-images.githubusercontent.com/85664248/131776586-839849d3-a33a-4987-bf15-7b7fb216dd56.png)

Our inkling is that it is a data type issue, but it's hard to put a finger on. Any assistance with this issue would be greatly appreciated!

**Comment by benjamin-tam** [comment]
Hi @MatthewOliverKing,

We have now open sourced https://github.com/csiro-robotics/dynamixel_interface which supports the X-series and is based off dynamixel_sdk. Hopefully this gives better results. The dynamixel_motor package is no longer supported.
